#!/bin/bash
# This script runs the full check suite, without any automatic fixes
set -euxo pipefail

# Run godot specific linting
poetry run --directory face_tracker/ gdformat .

cd face_tracker

poetry run ruff check --no-fix
poetry run ruff format --check
poetry run mypy --ignore-missing-imports crystalballer/ tests/
poetry run darglint \
  --strictness short \
  --docstring-style sphinx \
  --ignore-regex '^test_.*'
poetry run cruft check
echo "Lint successful!"