services:
  crystalballer:
    image: crystalballer
    volumes:
      # Give access to the camera USB device and maybe other hardware
      - "/dev/bus/usb:/dev/bus/usb"
      # Audio passthrough
      - "/run/user/${USER_ID:-1000}/pulse/native:/pulse-socket"
      - "~/.config/pulse/cookie:/root/.config/pulse/cookie:ro"
      # Model download caches
      - ".docker_cache/.cache/blobconverter:/root/.cache/blobconverter"
    environment:
      # Necessary for display passthrough
      DISPLAY: $DISPLAY
      # Audio passthrough
      PULSE_SERVER: "unix:/pulse-socket"
    network_mode: "host"  #  Recommended by luxonis docs for POE cameras
    privileged: true  # Not strictly required, but luxonis is not stable w/o this
    device_cgroup_rules:
      # As documented in https://docs.luxonis.com/projects/api/en/latest/install/#docker
      - 'c 189:* rmw'
    build:
      context: ./face_tracker
