#!/usr/bin/env bash

# Kill any existing networks and containers
docker compose down
docker container stop $(docker container ls -aq) && docker container rm $(docker container ls -aq)

# Allow X11 forwarding
xhost +

# Run the container, rebuilding images if necessary
docker compose run --build crystalballer "$@"